import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import "@mantine/notifications/styles.css";
import {
  ColorSchemeScript,
  createTheme,
  mantineHtmlProps,
  MantineProvider,
} from "@mantine/core";
import { Notifications } from "@mantine/notifications";

const theme = createTheme({
  defaultRadius: 8,
  components: {
    Accordion: {
      styles: {
        content: {
          padding: "0px",
        },
        control: {
          padding: "0px",
        },
      },
    },
    Tooltip: {
      styles: {
        tooltip: {
          border: "1px solid #DEE2E6",
        },
      },
    },
    Paper: {
      styles: {
        root: {
          overflow: "hidden",
        },
      },
    },
  },
  other: {
    borderColor: "#DEE2E6",
    couponColor: "#219538",
    couponBgColor: "#EBFFF4",
    onTopColor: "#FEBA00",
    onTopBgColor: "#FFFBEB",
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="light">
          <Notifications position="top-center" />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
